#!/bin/bash
set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE DATABASE ${DBNAME} WITH OWNER ${POSTGRES_USER} ENCODING 'UTF8' LC_COLLATE='en_US.utf8' LC_CTYPE='en_US.utf8' TEMPLATE=template0;
    GRANT ALL PRIVILEGES ON DATABASE ${DBNAME} TO ${POSTGRES_USER};
EOSQL
